#!/bin/bash
# Log file for debugging
# 目前支持少部分第三方软件apk 通过打开shell/apk-custom-packages.sh的注释来集成
source shell/apk-custom-packages.sh
echo "第三方apk软件包: $CUSTOM_PACKAGES"
LOGFILE="/tmp/uci-defaults-log.txt"
echo "Starting 99-custom.sh at $(date)" >> $LOGFILE
echo "编译固件大小为: $PROFILE MB"
echo "Include Docker: $INCLUDE_DOCKER"

echo "Create pppoe-settings"
mkdir -p  /home/build/immortalwrt/files/etc/config

# 创建pppoe配置文件 yml传入环境变量ENABLE_PPPOE等 写入配置文件 供99-custom.sh读取
cat << EOF > /home/build/immortalwrt/files/etc/config/pppoe-settings
enable_pppoe=${ENABLE_PPPOE}
pppoe_account=${PPPOE_ACCOUNT}
pppoe_password=${PPPOE_PASSWORD}
EOF

echo "cat pppoe-settings"
cat /home/build/immortalwrt/files/etc/config/pppoe-settings

if [ -z "$CUSTOM_PACKAGES" ]; then
  echo "⚪️ 未选择 任何第三方软件包"
else
  # ============= 同步第三方插件库==============
  # 同步第三方软件仓库run/apk
  echo "🔄 正在同步第三方软件仓库 Cloning run file repo..."
  git clone --depth=1 https://github.com/wukongdaily/apk.git /tmp/store-apk-repo

  # 拷贝 run/x86 下所有 run 文件和apk文件 到 extra-packages 目录
  mkdir -p /home/build/immortalwrt/extra-packages
  cp -r /tmp/store-apk-repo/run/x86/* /home/build/immortalwrt/extra-packages/

  echo "✅ Run files copied to extra-packages:"
  # 解压并拷贝apk到packages目录
  sh shell/apk-prepare-packages.sh
  ls -lah /home/build/immortalwrt/packages/
fi


# 输出调试信息
echo "$(date '+%Y-%m-%d %H:%M:%S') - 开始构建固件..."

# ============= imm仓库内的插件==============
# 定义所需安装的包列表 下列插件你都可以自行删减
PACKAGES=""
PACKAGES="$PACKAGES curl"
PACKAGES="$PACKAGES luci-i18n-diskman-zh-cn"
PACKAGES="$PACKAGES luci-i18n-firewall-zh-cn"
#25.12
PACKAGES="$PACKAGES luci-i18n-package-manager-zh-cn"
PACKAGES="$PACKAGES luci-i18n-ttyd-zh-cn"
PACKAGES="$PACKAGES openssh-sftp-server"
PACKAGES="$PACKAGES apinger"
PACKAGES="$PACKAGES apk-openssl"
PACKAGES="$PACKAGES attendedsysupgrade-common"
PACKAGES="$PACKAGES autocore"
PACKAGES="$PACKAGES automount"
PACKAGES="$PACKAGES banip"
PACKAGES="$PACKAGES base-files"
PACKAGES="$PACKAGES bind-dig"
PACKAGES="$PACKAGES bind-host"
PACKAGES="$PACKAGES block-mount"
PACKAGES="$PACKAGES busybox"
PACKAGES="$PACKAGES ca-bundle"
PACKAGES="$PACKAGES ca-certificates"
PACKAGES="$PACKAGES cfdisk"
PACKAGES="$PACKAGES cgi-io"
PACKAGES="$PACKAGES collectd-mod-cpufreq"
PACKAGES="$PACKAGES conntrack"
PACKAGES="$PACKAGES coreutils-stat"
PACKAGES="$PACKAGES cpupower"
PACKAGES="$PACKAGES cpusage"
PACKAGES="$PACKAGES crowdsec"
PACKAGES="$PACKAGES default-settings"
PACKAGES="$PACKAGES default-settings-chn"
PACKAGES="$PACKAGES dnsmasq-full"
PACKAGES="$PACKAGES dnsproxy"
PACKAGES="$PACKAGES dropbear"
PACKAGES="$PACKAGES e2fsprogs"
PACKAGES="$PACKAGES ethtool-full"
PACKAGES="$PACKAGES ethtool-lua"
PACKAGES="$PACKAGES fdisk"
PACKAGES="$PACKAGES fio"
PACKAGES="$PACKAGES firewall4"
PACKAGES="$PACKAGES fstools"
PACKAGES="$PACKAGES fwtool"
PACKAGES="$PACKAGES gawk"
PACKAGES="$PACKAGES getrandom"
PACKAGES="$PACKAGES git"
PACKAGES="$PACKAGES git-http"
PACKAGES="$PACKAGES grep"
PACKAGES="$PACKAGES grub2"
PACKAGES="$PACKAGES grub2-bios-setup"
PACKAGES="$PACKAGES grub2-efi"
PACKAGES="$PACKAGES htop"
PACKAGES="$PACKAGES i915-firmware-dmc"
PACKAGES="$PACKAGES intel-microcode"
PACKAGES="$PACKAGES iperf3"
PACKAGES="$PACKAGES iucode-tool"
PACKAGES="$PACKAGES jansson"
PACKAGES="$PACKAGES jq"
PACKAGES="$PACKAGES jshn"
PACKAGES="$PACKAGES jsonfilter"
PACKAGES="$PACKAGES kernel"
PACKAGES="$PACKAGES kmod-8139cp"
PACKAGES="$PACKAGES kmod-8139too"
PACKAGES="$PACKAGES kmod-amazon-ena"
PACKAGES="$PACKAGES kmod-amd-xgbe"
PACKAGES="$PACKAGES kmod-ata-ahci"
PACKAGES="$PACKAGES kmod-bnx2"
PACKAGES="$PACKAGES kmod-button-hotplug"
PACKAGES="$PACKAGES kmod-crypto-aead"
PACKAGES="$PACKAGES kmod-crypto-arc4"
PACKAGES="$PACKAGES kmod-crypto-crc32"
PACKAGES="$PACKAGES kmod-crypto-crc32c"
PACKAGES="$PACKAGES kmod-crypto-ecb"
PACKAGES="$PACKAGES kmod-crypto-hash"
PACKAGES="$PACKAGES kmod-crypto-hmac"
PACKAGES="$PACKAGES kmod-crypto-manager"
PACKAGES="$PACKAGES kmod-crypto-null"
PACKAGES="$PACKAGES kmod-crypto-rng"
PACKAGES="$PACKAGES kmod-crypto-sha1"
PACKAGES="$PACKAGES kmod-crypto-sha3"
PACKAGES="$PACKAGES kmod-crypto-sha512"
PACKAGES="$PACKAGES kmod-crypto-user"
PACKAGES="$PACKAGES kmod-drm-i915"
PACKAGES="$PACKAGES kmod-dwmac-intel"
PACKAGES="$PACKAGES kmod-e1000"
PACKAGES="$PACKAGES kmod-e1000e"
PACKAGES="$PACKAGES kmod-forcedeth"
PACKAGES="$PACKAGES kmod-fs-exfat"
PACKAGES="$PACKAGES kmod-fs-ext4"
PACKAGES="$PACKAGES kmod-fs-f2fs"
PACKAGES="$PACKAGES kmod-fs-ntfs3"
PACKAGES="$PACKAGES kmod-fs-vfat"
PACKAGES="$PACKAGES kmod-hid"
PACKAGES="$PACKAGES kmod-hid-generic"
PACKAGES="$PACKAGES kmod-hwmon-core"
PACKAGES="$PACKAGES kmod-i2c-algo-bit"
PACKAGES="$PACKAGES kmod-i2c-core"
PACKAGES="$PACKAGES kmod-i2c-i801"
PACKAGES="$PACKAGES kmod-i40e"
PACKAGES="$PACKAGES kmod-igb"
PACKAGES="$PACKAGES kmod-igbvf"
PACKAGES="$PACKAGES kmod-igc"
PACKAGES="$PACKAGES kmod-inet-diag"
PACKAGES="$PACKAGES kmod-input-core"
PACKAGES="$PACKAGES kmod-input-evdev"
PACKAGES="$PACKAGES kmod-ixgbe"
PACKAGES="$PACKAGES kmod-ixgbevf"
PACKAGES="$PACKAGES kmod-lib-crc-ccitt"
PACKAGES="$PACKAGES kmod-lib-crc16"
PACKAGES="$PACKAGES kmod-lib-crc32c"
PACKAGES="$PACKAGES kmod-libeth"
PACKAGES="$PACKAGES kmod-libie"
PACKAGES="$PACKAGES kmod-libphy"
PACKAGES="$PACKAGES kmod-macvlan"
PACKAGES="$PACKAGES kmod-mdio"
PACKAGES="$PACKAGES kmod-mdio-devres"
PACKAGES="$PACKAGES kmod-mii"
PACKAGES="$PACKAGES kmod-mppe"
PACKAGES="$PACKAGES kmod-net-selftests"
PACKAGES="$PACKAGES kmod-nf-conntrack"
PACKAGES="$PACKAGES kmod-nf-conntrack-netlink"
PACKAGES="$PACKAGES kmod-nf-conntrack6"
PACKAGES="$PACKAGES kmod-nf-flow"
PACKAGES="$PACKAGES kmod-nf-log"
PACKAGES="$PACKAGES kmod-nf-log6"
PACKAGES="$PACKAGES kmod-nf-nat"
PACKAGES="$PACKAGES kmod-nf-nat6"
PACKAGES="$PACKAGES kmod-nf-nathelper"
PACKAGES="$PACKAGES kmod-nf-reject"
PACKAGES="$PACKAGES kmod-nf-reject6"
PACKAGES="$PACKAGES kmod-nfnetlink"
PACKAGES="$PACKAGES kmod-nft-core"
PACKAGES="$PACKAGES kmod-nft-fib"
PACKAGES="$PACKAGES kmod-nft-fullcone"
PACKAGES="$PACKAGES kmod-nft-nat"
PACKAGES="$PACKAGES kmod-nft-offload"
PACKAGES="$PACKAGES kmod-nft-tproxy"
PACKAGES="$PACKAGES kmod-nls-base"
PACKAGES="$PACKAGES kmod-nls-cp437"
PACKAGES="$PACKAGES kmod-nls-iso8859-1"
PACKAGES="$PACKAGES kmod-nls-utf8"
PACKAGES="$PACKAGES kmod-nvme"
PACKAGES="$PACKAGES kmod-pcnet32"
PACKAGES="$PACKAGES kmod-phy-ax88796b"
PACKAGES="$PACKAGES kmod-phylink"
PACKAGES="$PACKAGES kmod-ppp"
PACKAGES="$PACKAGES kmod-pppoe"
PACKAGES="$PACKAGES kmod-pppox"
PACKAGES="$PACKAGES kmod-pps"
PACKAGES="$PACKAGES kmod-ptp"
PACKAGES="$PACKAGES kmod-r8101"
PACKAGES="$PACKAGES kmod-r8125"
PACKAGES="$PACKAGES kmod-r8126"
PACKAGES="$PACKAGES kmod-r8168"
PACKAGES="$PACKAGES kmod-scsi-core"
PACKAGES="$PACKAGES kmod-slhc"
PACKAGES="$PACKAGES kmod-tg3"
PACKAGES="$PACKAGES kmod-tulip"
PACKAGES="$PACKAGES kmod-usb-common"
PACKAGES="$PACKAGES kmod-usb-core"
PACKAGES="$PACKAGES kmod-usb-hid"
PACKAGES="$PACKAGES kmod-usb-net"
PACKAGES="$PACKAGES kmod-usb-net-asix"
PACKAGES="$PACKAGES kmod-usb-net-asix-ax88179"
PACKAGES="$PACKAGES kmod-usb-net-rtl8150"
PACKAGES="$PACKAGES kmod-usb-net-rtl8152-vendor"
PACKAGES="$PACKAGES kmod-usb-storage"
PACKAGES="$PACKAGES kmod-usb-storage-extras"
PACKAGES="$PACKAGES kmod-usb-storage-uas"
PACKAGES="$PACKAGES kmod-vmxnet3"
PACKAGES="$PACKAGES libblkid"
PACKAGES="$PACKAGES libblobmsg-json"
PACKAGES="$PACKAGES libc"
PACKAGES="$PACKAGES libcomerr"
PACKAGES="$PACKAGES libe2p"
PACKAGES="$PACKAGES libext2fs"
PACKAGES="$PACKAGES libf2fs"
PACKAGES="$PACKAGES libfdisk"
PACKAGES="$PACKAGES libgcc"
PACKAGES="$PACKAGES libgmp"
PACKAGES="$PACKAGES libiwinfo"
PACKAGES="$PACKAGES libiwinfo-data"
PACKAGES="$PACKAGES libjson-c"
PACKAGES="$PACKAGES libjson-script"
PACKAGES="$PACKAGES liblucihttp"
PACKAGES="$PACKAGES liblucihttp-ucode"
PACKAGES="$PACKAGES libmbedtls"
PACKAGES="$PACKAGES libmnl"
PACKAGES="$PACKAGES libncurses"
PACKAGES="$PACKAGES libncurses-dev"
PACKAGES="$PACKAGES libnetfilter-conntrack"
PACKAGES="$PACKAGES libnettle"
PACKAGES="$PACKAGES libnfnetlink"
PACKAGES="$PACKAGES libnftnl"
PACKAGES="$PACKAGES libnl-tiny"
PACKAGES="$PACKAGES libopenssl"
PACKAGES="$PACKAGES libpthread"
PACKAGES="$PACKAGES librt"
PACKAGES="$PACKAGES libsensors"
PACKAGES="$PACKAGES libsmartcols"
PACKAGES="$PACKAGES libss"
PACKAGES="$PACKAGES libsysfs"
PACKAGES="$PACKAGES libubox"
PACKAGES="$PACKAGES libubus"
PACKAGES="$PACKAGES libuci"
PACKAGES="$PACKAGES libuclient"
PACKAGES="$PACKAGES libucode"
PACKAGES="$PACKAGES libudebug"
PACKAGES="$PACKAGES libustream-openssl"
PACKAGES="$PACKAGES libuuid"
PACKAGES="$PACKAGES lm-sensors"
PACKAGES="$PACKAGES logd"
PACKAGES="$PACKAGES lsblk"
PACKAGES="$PACKAGES lualanes"
PACKAGES="$PACKAGES luci"
PACKAGES="$PACKAGES luci-app-adguardhome"
PACKAGES="$PACKAGES luci-app-attendedsysupgrade"
PACKAGES="$PACKAGES luci-app-filemanager"
PACKAGES="$PACKAGES luci-app-firewall"
PACKAGES="$PACKAGES luci-app-mosdns"
PACKAGES="$PACKAGES luci-app-openclash"
PACKAGES="$PACKAGES luci-app-package-manager"
PACKAGES="$PACKAGES luci-base"
PACKAGES="$PACKAGES luci-i18n-arpbind-zh-cn"
PACKAGES="$PACKAGES luci-i18n-attendedsysupgrade-zh-cn"
PACKAGES="$PACKAGES luci-i18n-banip-zh-cn"
PACKAGES="$PACKAGES luci-i18n-base-zh-cn"
PACKAGES="$PACKAGES luci-i18n-cpulimit-zh-cn"
PACKAGES="$PACKAGES luci-i18n-crowdsec-firewall-bouncer-zh-cn"
PACKAGES="$PACKAGES luci-i18n-diskman-zh-cn"
PACKAGES="$PACKAGES luci-i18n-dockerman-zh-cn"
PACKAGES="$PACKAGES luci-i18n-filemanager-zh-cn"
PACKAGES="$PACKAGES luci-i18n-firewall-zh-cn"
PACKAGES="$PACKAGES luci-i18n-mosdns-zh-cn"
PACKAGES="$PACKAGES luci-i18n-openlist-zh-cn"
PACKAGES="$PACKAGES luci-i18n-package-manager-zh-cn"
PACKAGES="$PACKAGES luci-i18n-ttyd-zh-cn"
PACKAGES="$PACKAGES luci-i18n-uhttpd-zh-cn"
PACKAGES="$PACKAGES luci-layer2"
PACKAGES="$PACKAGES luci-lib-uqr"
PACKAGES="$PACKAGES luci-light"
PACKAGES="$PACKAGES luci-mod-admin-full"
PACKAGES="$PACKAGES luci-mod-network"
PACKAGES="$PACKAGES luci-mod-status"
PACKAGES="$PACKAGES luci-mod-system"
PACKAGES="$PACKAGES luci-proto-ipv6"
PACKAGES="$PACKAGES luci-proto-ppp"
PACKAGES="$PACKAGES luci-proto-wireguard"
PACKAGES="$PACKAGES luci-ssl"
PACKAGES="$PACKAGES luci-theme-bootstrap"
PACKAGES="$PACKAGES luci-theme-material"
PACKAGES="$PACKAGES luci-theme-proton2025"
PACKAGES="$PACKAGES lyaml"
PACKAGES="$PACKAGES mkf2fs"
PACKAGES="$PACKAGES mosdns"
PACKAGES="$PACKAGES mtd"
PACKAGES="$PACKAGES netatop"
PACKAGES="$PACKAGES netifd"
PACKAGES="$PACKAGES nftables"
PACKAGES="$PACKAGES nftables-json"
PACKAGES="$PACKAGES ntfs3-mount"
PACKAGES="$PACKAGES odhcp6c"
PACKAGES="$PACKAGES odhcpd-ipv6only"
PACKAGES="$PACKAGES openssh-sftp-server"
PACKAGES="$PACKAGES openssl-util"
PACKAGES="$PACKAGES openwrt-keyring"
PACKAGES="$PACKAGES owut"
PACKAGES="$PACKAGES partx-utils"
PACKAGES="$PACKAGES pciutils"
PACKAGES="$PACKAGES ppp"
PACKAGES="$PACKAGES ppp-mod-pppoe"
PACKAGES="$PACKAGES procd"
PACKAGES="$PACKAGES procd-seccomp"
PACKAGES="$PACKAGES procd-ujail"
PACKAGES="$PACKAGES python3"
PACKAGES="$PACKAGES python3-base"
PACKAGES="$PACKAGES python3-codecs"
PACKAGES="$PACKAGES python3-light"
PACKAGES="$PACKAGES q"
PACKAGES="$PACKAGES qrencode"
PACKAGES="$PACKAGES rpcd"
PACKAGES="$PACKAGES rpcd-mod-file"
PACKAGES="$PACKAGES rpcd-mod-iwinfo"
PACKAGES="$PACKAGES rpcd-mod-luci"
PACKAGES="$PACKAGES rpcd-mod-rpcsys"
PACKAGES="$PACKAGES rpcd-mod-rrdns"
PACKAGES="$PACKAGES rpcd-mod-ucode"
PACKAGES="$PACKAGES sed"
PACKAGES="$PACKAGES sfdisk"
PACKAGES="$PACKAGES shellsync"
PACKAGES="$PACKAGES sysfsutils"
PACKAGES="$PACKAGES tcpdump"
PACKAGES="$PACKAGES terminfo"
PACKAGES="$PACKAGES ubox"
PACKAGES="$PACKAGES ubus"
PACKAGES="$PACKAGES ubusd"
PACKAGES="$PACKAGES uci"
PACKAGES="$PACKAGES uclient-fetch"
PACKAGES="$PACKAGES ucode"
PACKAGES="$PACKAGES ucode-mod-fs"
PACKAGES="$PACKAGES ucode-mod-html"
PACKAGES="$PACKAGES ucode-mod-log"
PACKAGES="$PACKAGES ucode-mod-math"
PACKAGES="$PACKAGES ucode-mod-ubus"
PACKAGES="$PACKAGES ucode-mod-uci"
PACKAGES="$PACKAGES ucode-mod-uclient"
PACKAGES="$PACKAGES ucode-mod-uloop"
PACKAGES="$PACKAGES uhttpd"
PACKAGES="$PACKAGES uhttpd-mod-ubus"
PACKAGES="$PACKAGES unetd"
PACKAGES="$PACKAGES urandom-seed"
PACKAGES="$PACKAGES urngd"
PACKAGES="$PACKAGES usbutils"
PACKAGES="$PACKAGES usign"
PACKAGES="$PACKAGES v2dat"
PACKAGES="$PACKAGES v2ray-geoip"
PACKAGES="$PACKAGES v2ray-geosite"
PACKAGES="$PACKAGES yate-mod-cpuload"
PACKAGES="$PACKAGES zlib"

# 文件管理器
PACKAGES="$PACKAGES luci-i18n-filemanager-zh-cn"
# ======== shell/apk-custom-packages.sh =======
# 合并imm仓库以外的第三方插件 暂时注释
PACKAGES="$PACKAGES $CUSTOM_PACKAGES"


# 判断是否需要编译 Docker 插件
if [ "$INCLUDE_DOCKER" = "yes" ]; then
    PACKAGES="$PACKAGES luci-i18n-dockerman-zh-cn"
    echo "Adding package: luci-i18n-dockerman-zh-cn"
fi

# 若构建openclash 则添加内核
if echo "$PACKAGES" | grep -q "luci-app-openclash"; then
    echo "✅ 已选择 luci-app-openclash，添加 openclash core"
    mkdir -p files/etc/openclash/core
    # Download clash_meta
    META_URL="https://raw.githubusercontent.com/vernesong/OpenClash/core/master/meta/clash-linux-amd64-v1.tar.gz"
    wget -qO- $META_URL | tar xOvz > files/etc/openclash/core/clash_meta
    chmod +x files/etc/openclash/core/clash_meta
    # Download GeoIP and GeoSite
    wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat -O files/etc/openclash/GeoIP.dat
    wget -q https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat -O files/etc/openclash/GeoSite.dat
    # Download latest openclash Client
    URL=$(curl -s https://api.github.com/repos/vernesong/OpenClash/releases/latest \
      | grep "browser_download_url.*apk" \
      | head -n1 \
      | cut -d '"' -f 4)
    echo "OpenClash latest apk: $URL"
    wget "$URL" -P /home/build/immortalwrt/packages/
else
    echo "⚪️ 未选择 luci-app-openclash"
fi

if echo "$PACKAGES" | grep -q "luci-app-ssr-plus"; then
    echo "✅ 已选择 luci-app-ssr-plus，添加 mihomo core"
    mkdir -p files/usr/bin
    # Download mihomo
    MIHOMO_URL="https://github.com/MetaCubeX/mihomo/releases/download/v1.19.24/mihomo-linux-amd64-compatible-v1.19.24.gz"
    mkdir -p files/usr/bin
    wget -qO- "$MIHOMO_URL" | gzip -dc > files/usr/bin/mihomo
    chmod +x files/usr/bin/mihomo
    echo "✅ 已下载 mihomo core"
    ls -lah files/usr/bin
else
    echo "⚪️ 未选择 luci-app-ssr-plus"
fi

# 构建镜像
echo "$(date '+%Y-%m-%d %H:%M:%S') - Building image with the following packages:"
echo "$PACKAGES"

make image PROFILE="generic" PACKAGES="$PACKAGES" FILES="/home/build/immortalwrt/files" ROOTFS_PARTSIZE=$PROFILE

if [ $? -ne 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - Error: Build failed!"
    exit 1
fi

echo "$(date '+%Y-%m-%d %H:%M:%S') - Build completed successfully."
